import os
import torch
import torch.nn.functional as F
from fastapi import FastAPI, File, UploadFile, HTTPException
from PIL import Image
import io
from torchvision import transforms
from model import get_model

app = FastAPI(title="PyTorch Inference Engine", version="1.0")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = get_model(architecture="simple_cnn", num_classes=10)
model_path = os.getenv("MODEL_PATH", "/app/checkpoints/model.pth")

model_loaded = False
if os.path.exists(model_path):
    try:
        # Load the checkpoint structure generated by the starter code
        checkpoint = torch.load(model_path, map_location=device)
        if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
            model.load_state_dict(checkpoint["model_state_dict"])
        else:
            model.load_state_dict(checkpoint)
        model.eval().to(device)
        model_loaded = True
        print(f"Successfully loaded model weight metrics from: {model_path}")
    except Exception as e:
        print(f"Failed to load checkpoint layout attributes: {str(e)}")
else:
    print(f"Warning: Checkpoint tracking reference missing at {model_path}. Evaluation running via random layers.")
    model.eval().to(device)

# Standard CIFAR-10 reference transformations matching get_transforms(train=False)
transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.4914, 0.4822, 0.4465],
        std=[0.2470, 0.2435, 0.2616],
    ),
])

@app.get("/health", status_code=200)
def health_check():
    """Returns 200 response configuration structure if model maps cleanly inside runtime layers."""
    if model is not None:
        return {"status": "healthy", "model_loaded": model_loaded}
    raise HTTPException(status_code=503, detail="Inference application unit uninitialized")

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Invalid transmission file media payload extension format type.")
    
    try:
        payload = await file.read()
        image = Image.open(io.BytesIO(payload)).convert("RGB")
        tensor = transform(image).unsqueeze(0).to(device)
        
        with torch.no_grad():
            outputs = model(tensor)
            probabilities = F.softmax(outputs, dim=1).squeeze(0)
            
        return {
            "predicted_class": int(torch.argmax(probabilities).item()),
            "probabilities": [round(float(p), 5) for p in probabilities.tolist()]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
